config/routes.rb
Rails.application.routes.draw do
  resources :res_dates

  root 'reservations#index'
  resources :rooms
  resources :reservations
  get 'reservations/by/date', to: 'reservations#show_by_date'

end

app/models/res_date.rb
class ResDate < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  after_initialize do |reservation|
    @room = Room.find_by room_number: self.room_id
  end
  
  after_save :set_room_status
  before_destroy :check_room_status
  
  room_numbers = Array (100..111) #Room numbers are 100 through 111 for this hotel.
  
  validates :room_id, inclusion: { in: room_numbers, message: "%{value} is not a valid room number" }
  
  private
    def set_room_status
      @room.reserved = true
      @room.save
    end
    
    def check_room_status
      @room.reserved = false
      @room.save
    end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/res_dates_controller.rb
class ResDatesController < ApplicationController
  before_action :set_res_date, only: [:show, :edit, :update, :destroy]

  # GET /res_dates
  # GET /res_dates.json
  def index
    @res_dates = ResDate.all
  end

  # GET /res_dates/1
  # GET /res_dates/1.json
  def show
  end

  # GET /res_dates/new
  def new
    @res_date = ResDate.new
  end

  # GET /res_dates/1/edit
  def edit
  end

  # POST /res_dates
  # POST /res_dates.json
  def create
    @res_date = ResDate.new(res_date_params)

    respond_to do |format|
      if @res_date.save
        format.html { redirect_to @res_date, notice: 'Res date was successfully created.' }
        format.json { render :show, status: :created, location: @res_date }
      else
        format.html { render :new }
        format.json { render json: @res_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /res_dates/1
  # PATCH/PUT /res_dates/1.json
  def update
    respond_to do |format|
      if @res_date.update(res_date_params)
        format.html { redirect_to @res_date, notice: 'Res date was successfully updated.' }
        format.json { render :show, status: :ok, location: @res_date }
      else
        format.html { render :edit }
        format.json { render json: @res_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /res_dates/1
  # DELETE /res_dates/1.json
  def destroy
    @res_date.destroy
    respond_to do |format|
      format.html { redirect_to res_dates_url, notice: 'Res date was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_res_date
      @res_date = ResDate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def res_date_params
      params.require(:res_date).permit(:res_date)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
    @rooms = Room.all
    @rooms_status = []
    @rooms.each do |room|
      if room.reserved == true
	  @rooms_status.push("hotel-res-room-cell")
      else
	  @rooms_status.push("hotel-ava-room-cell")
      end
    end
    @today_res = []
    @reservations.each do |res|
      if res.reservation_date == Date.today
	  @today_res[res.id] = (res.room_id)
      end
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_by_date
    date_params = params[:date]
    year = date_params[:year]
    month = date_params[:month]
    day = date_params[:day]
    date = year + "-" + month + "-" + day
    @reservations = Reservation.where(reservation_date: date.to_date)
    @rooms = Room.all
    @rooms_status = []
    @rooms.each do |room|
      if room.reserved == true
    @rooms_status.push("hotel-res-room-cell")
      else
    @rooms_status.push("hotel-ava-room-cell")
      end
    end
    @today_res = []
    @reservations.each do |res|
      if res.reservation_date == date.to_date
    @today_res[res.id] = (res.room_id)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:room_id, :reservation_date)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @reservations = Reservation.all
    @res_for_this = @reservations.where(room_id: @room.room_number)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number, :reserved)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/res_dates_helper.rb
module ResDatesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <nav>
   <a href="/reservations/">Reservations</a> |
   <a href="/rooms/">Rooms</a> |
   <a href="/res_dates/">Reservation Dates</a>
  </nav>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/res_dates/_form.html.erb
<%= form_for(@res_date) do |f| %>
  <% if @res_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@res_date.errors.count, "error") %> prohibited this res_date from being saved:</h2>

      <ul>
      <% @res_date.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :res_date %><br>
    <%= f.datetime_select :res_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/res_dates/edit.html.erb
<h1>Editing res_date</h1>

<%= render 'form' %>

<%= link_to 'Show', @res_date %> |
<%= link_to 'Back', res_dates_path %>

app/views/res_dates/index.html.erb
<h1>Listing res_dates</h1>

<table>
  <thead>
    <tr>
      <th>Res date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @res_dates.each do |res_date| %>
      <tr>
        <td><%= res_date.res_date %></td>
        <td><%= link_to 'Show', res_date %></td>
        <td><%= link_to 'Edit', edit_res_date_path(res_date) %></td>
        <td><%= link_to 'Destroy', res_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Res date', new_res_date_path %>

app/views/res_dates/new.html.erb
<h1>New res_date</h1>

<%= render 'form' %>

<%= link_to 'Back', res_dates_path %>

app/views/res_dates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Res date:</strong>
  <%= @res_date.res_date %>
</p>

<%= link_to 'Edit', edit_res_date_path(@res_date) %> |
<%= link_to 'Back', res_dates_path %>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.number_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :reservation_date %><br>
    <%= f.date_select :reservation_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<% today = Date.today.to_formatted_s(:month_day_year) %>
<h3>Room status for <span id="hotel-date"><%= today %></span> (<span class="hotel-ava-text">available</span>/<span class="hotel-res-text">reserved</span>):</h3>

<%= form_tag("/reservations/by/date", method: "get" ) do %>
  <%= select_date(Time.now) %>  <%= submit_tag("Update") %>
<% end %>

<table class="hotel-room-table">
  <tbody>
    <tr>
      <td class="hotel-vert-hall-cell"></td>

      <% this_room = 100 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 101 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 102 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <td class="hotel-vert-hall-cell"></td>

      <% this_room = 103 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 104 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 105 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

    </tr>
    <tr>
      <td class="hotel-hori-hall-cell" colspan="8"></td>
    </tr>
    <tr>

      <% this_room = 106 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 107 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 108 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 109 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 110 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 111 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <td class="hotel-vert-hall-cell"></td>
      <td class="hotel-vert-hall-cell"></td>
    </tr>
  </tbody>
</table>

<h3>Reservation Detail:</h3>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Reservation date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.room_id %></td>
        <td class="hotel-res-dates" data-res-id="<%= reservation.id %>"><%= reservation.reservation_date.to_formatted_s(:month_day_year) %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room_id %>
</p>

<p>
  <strong>Reservation date:</strong>
  <%= @reservation.reservation_date %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/show_by_date.html.erb
<% today = Date.today.to_formatted_s(:month_day_year) %>
<h3>Room status for <span id="hotel-date"><%= today %></span> (<span class="hotel-ava-text">available</span>/<span class="hotel-res-text">reserved</span>):</h3>

<%= form_tag("/reservations/by/date", method: "get" ) do %>
  <%= select_date(Time.now) %>  <%= submit_tag("Update") %>
<% end %>

<table class="hotel-room-table">
  <tbody>
    <tr>
      <td class="hotel-vert-hall-cell"></td>

      <% this_room = 100 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 101 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 102 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <td class="hotel-vert-hall-cell"></td>

      <% this_room = 103 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 104 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 105 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

    </tr>
    <tr>
      <td class="hotel-hori-hall-cell" colspan="8"></td>
    </tr>
    <tr>

      <% this_room = 106 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 107 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 108 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 109 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 110 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <% this_room = 111 %>
      <% if @today_res.include?(this_room) %>
        <td class="hotel-res-room-cell" id='<%= "#{this_room}" %>'>
        <% this_id = @today_res.index(this_room) %>
        <%= link_to "#{this_room}", edit_reservation_path(this_id) %>
        </td>
      <% else %>
        <td class="hotel-ava-room-cell" id='<%= "#{this_room}" %>'>
        <%= "#{this_room}" %>
        </td>
      <% end %>

      <td class="hotel-vert-hall-cell"></td>
      <td class="hotel-vert-hall-cell"></td>
    </tr>
  </tbody>
</table>

<h3>Reservation Detail:</h3>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Reservation date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.room_id %></td>
        <td class="hotel-res-dates" data-res-id="<%= reservation.id %>"><%= reservation.reservation_date.to_formatted_s(:month_day_year) %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_number %><br>
    <%= f.number_field :room_number %>
  </div>
  <div class="field">
    <%= f.label :reserved %><br>
    <%= f.check_box :reserved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Reserved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.reserved %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Room reservations:</strong>
    <% @res_for_this.each do |res| %>
      <p><%= res.reservation_date %></p>
    <% end %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Reserved:</strong>
  <%= @room.reserved %>
</p>

<p>
  <strong>ID:</strong>
  <%= @room.id %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>